<?php
return[
    'admin'=>'追梦之门',
    'admin_index'=>'竹玉轩',
    'user_add'=>'添加用户',
    'user_lists'=>'用户列表',
    'cate_article_add'=>'添加文章分类',
    'cate_article_index'=>'文章分类列表',
    'article_add'=>'添加文章',
    'article_index'=>'文章列表',
];